version: ${VERSION}
services:
    psql-database:
        hostname: psql-database
        container_name: psql-database
        image: postgres:13.9-bullseye
        environment:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            PGDATA: /data/postgres
        restart: unless-stopped
    frontend:
        hostname: frontend
        container_name: frontend
        tty: true
        depends_on:
            - backend
        volumes:
            - opencapture-src:/var/www/html/opencapture/
        build:
            context: .
            dockerfile: DockerfileApache2
        ports:
            - 8080:80
    backend:
        hostname: backend
        container_name: backend
        tty: true
        volumes:
              - opencapture-src:/var/www/html/opencapture/
        build:
            context: .
            dockerfile: Dockerfile
            args:
                custom_id: edissyum
                version: ${VERSION}
volumes:
    opencapture-src: